version: '3'
services:
  postgres:
    network_mode: bridge
    image: arminc/clair-db:latest
  clair:
    network_mode: bridge
    depends_on:
      - postgres
    build: .
    ports:
      - "6060:6060"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - postgres
  # scanner:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile-client
  #   network_mode: bridge
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   links:
  #     - clair
  #   depends_on:
  #     - clair